name: Gatsby Publish
on:
  pull_request:
    branches:
      - gh-pages
    paths-ignore:
      - '**/README.md'
  push:
    branches:
      - gh-pages
    paths-ignore:
      - '**/README.md'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.TOKEN }}
          deploy-branch: master
          skip-publish: false